version: '3.8'
services:
  db:
    build:
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=default_database
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
